# =========================================================
# PARAMETERS
# =========================================================
ROLLING_WINDOW = 100
BUY_Z = 1.0
SHORT_Z = 1.0
ABNORMAL_LOW_Z = 1.5
ABNORMAL_HIGH_Z = 2.0
EVENT_WINDOW_MINUTES = 10

TOTAL_CAPITAL = 10_000_000
LONG_BOOK_CAPITAL = 0.50 * TOTAL_CAPITAL
SHORT_BOOK_CAPITAL = 0.50 * TOTAL_CAPITAL
PER_NAME_CAPITAL = 25_000

FORCE_EXIT_IGNORES_PARTICIPATION = True
SLIPPAGE_SPREAD_FRAC = 0.25
MINUTES_PER_YEAR = 252 * 390
ANNUALIZATION_MINUTES = MINUTES_PER_YEAR

# validation / cleaning settings
DROP_CROSSED_MARKETS = True
ALLOW_LOCKED_MARKETS = True
DROP_NEGATIVE_VOLUME = True
PRINT_VALIDATION_SUMMARY = True

# hedge / reporting settings
REBALANCE_HEDGE_EVERY_MINUTE = True
PLOT_FIGSIZE = (12, 6)